version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - playhive-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

networks:
  playhive-net:
    external: true

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local