spring:
  profiles:
    active: prod
    include: auth, mail, swagger
  application:
    name: myteam-server

management:
  endpoints:
    web:
      exposure:
        include: *
  #        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
      access: read_only
    health:
      show-details: always
  security:
    enabled: false