spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: playhive
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 1000 #최적화 옵션
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: none
      #  create	기존테이블을 삭제하고 다시 생성
      #  create-drop 기존테이블을 삭제하고 다시생성. 종료 시점에 테이블삭제
      #  update	변경된 스키마 적용 (운영 DB 에서 사용X)
      #  validate Entity 와 테이블이 정상 매핑 되었는지 확인
      #  none 기존테이블을 더 이상 건드리지 않음.
    open-in-view: true

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}

logging:
  level:
    root: info  # 전체 로그를 INFO, DEBUG, WARN 수준으로 설정
    org.springframework.security: warn
    org.springframework.web: warn
    com.myteam.server: info
    # 필요 시 특정 SQL 로그를 추가하거나 Hibernate SQL 로그를 설정
    hibernate.SQL: warn
    org.springframework.boot.autoconfigure: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: WARN
    # 아직 Thymeleaf 를 사용하지 않기 때문에, 경고 메세지를 제거합니다.
    spring.thymeleaf.check-template-location: false
    org.hibernate.type: INFO

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  region: ${MINIO_REGION}
  bucket: ${MINIO_BUCKET}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  bucket: ${AWS_BUCKET}

playhive:
  control:
    aesSecretKey: ${AES_SECRET_KEY}
    aesIv: ${AES_IV}
